# lib/wgshield_ops.sh - Operações de containers (install/start/stop/update/remove/status/logs/shell)

install_comp() {
    local comp="$1"
    local silent="${2:-false}"
    local display default_ports repo container dir ports

    if ! comp_info_valid "$comp"; then
        err "${ERR_UNKNOWN_COMP}: $comp"
    fi

    # Direct parsing without parse_comp to avoid subshell issues
    local _cat _name _display _ports _pubports _repo _container _dir
    local _found=0
    while IFS='|' read -r _cat _name _display _ports _pubports _repo _container _dir; do
        [ -z "$_name" ] && continue
        if [ "$_name" = "$comp" ]; then
            display="$_display"
            default_ports="$_ports"
            repo="$_repo"
            container="$_container"
            dir="$_dir"
            _found=1
            break
        fi
    done <<< "$COMPONENTS"

    ports="$default_ports"

    # Skip interactive prompts in silent mode (used by install animation)
    if [ "$silent" = "true" ]; then
        # Skip if container already running
        if get_container_status "$container" | grep -q "running"; then
            return 0
        fi
        if ! detect_vps_state >/dev/null 2>&1; then
            warn "${ERR_PORT_CONFLICT}"
        fi
        create_backup "vps" "before-install-${comp}" >/dev/null 2>&1
        if ! has_docker; then
            install_docker >/dev/null 2>&1
        fi
        mkdir -p "$dir"
        if [ -d "$dir/.git" ]; then
            (cd "$dir" && git pull --quiet) || true
        else
            git clone "${GITHUB_BASE}/${repo}.git" "$dir" >/dev/null 2>&1 || err "${ERR_CLONE_FAIL} ${GITHUB_BASE}/${repo}.git"
        fi
        if [ -f "$dir/.env.example" ] && [ ! -f "$dir/.env" ]; then
            cp "$dir/.env.example" "$dir/.env"
        fi
        # Special handling for wg-easy
        if [ "$comp" = "wg-easy" ]; then
            local wg_host wg_pass raw_output raw_hash
            wg_host=$(curl -s4 ifconfig.me 2>/dev/null || echo "YOUR_IP")
            wg_pass=$(openssl rand -hex 8)
            raw_output=$(docker run --rm ghcr.io/wg-easy/wg-easy wgpw "$wg_pass" 2>/dev/null)
            raw_hash=$(echo "$raw_output" | sed "s|PASSWORD_HASH=||" | tr -d "'" | tr -d '\r' | tr -d '\n')

            # Write .env fresh (avoids sed escaping issues)
            cat > "$dir/.env" << ENVEOF
# WG-Easy Environment Variables
# Generated by wgshield.sh

WG_HOST=${wg_host}
PASSWORD_HASH=${raw_hash}
WG_DEFAULT_DNS=10.8.1.3
WG_PORT_UDP=51820
WG_PORT_TCP=51821
WG_PASSWORD=${wg_pass}
ENVEOF
            chmod 600 "$dir/.env" 2>/dev/null || true
        fi
        chmod +x "$dir"/*.sh 2>/dev/null || true
        (cd "$dir" && docker compose up -d 2>&1) >/dev/null
        sleep 3
        return 0
    fi

    detect_vps_state
    local vps_ok=$?
    if [ $vps_ok -ne 0 ]; then
        warn "${ERR_PORT_CONFLICT}"
        confirm "${PROMPT_CONTINUE}" || return 0
    fi

    echo ""
    echo -e "  ${BD}${C}=== $display ===${NC}"
    echo ""
    echo "    ${MSG_INST_IMAGE}     $display"
    echo "    ${MSG_INFO_PORT}      $default_ports"
    echo "    ${MSG_INFO_CUSTOM_PORT}     $dir"
    echo "    Repo:       ${GITHUB_BASE}/${repo}"
    echo ""

    if [ "$AUTO_YES" != "true" ]; then
        read -rp "  ${MSG_INST_CUSTOMIZE}" cust
        if [[ "$cust" =~ ^[yY]$ ]]; then
            echo ""
            read -rp "  ${PROMPT_FOLDER}" x; [ -n "$x" ] && dir="$x"
            read -rp "  ${PROMPT_PORT}" x; [ -n "$x" ] && ports="$x"
            echo ""
            echo -e "  ${BD}=== ${MSG_INST_SUMMARY} ===${NC}"
            echo ""
            printf "    %-16s → %-30s (port %s)\n" "$display" "$dir" "$ports"
            echo ""
        fi
    fi

    confirm "${PROMPT_CONFIRM}" || return 0

    create_backup "vps" "before-install-${comp}"

    if ask_firewall_choice; then
        IFS=',' read -ra PORT_ARRAY <<< "$ports"
        for port_item in "${PORT_ARRAY[@]}"; do
            open_port "$port_item" "$display"
        done
        log "${LOG_PORT_OPENED} $ports"
    fi

    local avail_kb
    avail_kb=$(df --output=avail "$dir" 2>/dev/null | tail -1 | tr -d ' ')
    if [ -n "$avail_kb" ] && [ "$avail_kb" -lt 512000 ] 2>/dev/null; then
        warn "${ERR_DISK_SPACE} ($(( avail_kb / 1024 ))MB ${MSG_DISK_FREE}). ${MSG_DOCK_INSTALLING}: 500MB+"
        confirm "${PROMPT_CONFIRM}" || return 1
    fi

    mkdir -p "$dir"

    if [ -d "$dir/.git" ]; then
        spinner "${MSG_LOG_UPDATING} $display"
        (cd "$dir" && git pull --quiet) || true
    else
        spinner "${MSG_LOG_CLONING} $display"
        if ! git clone "${GITHUB_BASE}/${repo}.git" "$dir" 2>&1; then
            err "${ERR_CLONE_FAIL} ${GITHUB_BASE}/${repo}.git"
        fi
    fi

    if [ -f "$dir/.env.example" ] && [ ! -f "$dir/.env" ]; then
        cp "$dir/.env.example" "$dir/.env"
    fi

    # Special handling for wg-easy: generate WG_HOST and PASSWORD_HASH
    if [ "$comp" = "wg-easy" ]; then
        spinner "${MSG_LOG_GENERATING_ENV}"
        local wg_host wg_pass raw_output raw_hash
        wg_host=$(curl -s4 ifconfig.me 2>/dev/null || echo "YOUR_IP")
        wg_pass=$(openssl rand -hex 8)
        raw_output=$(docker run --rm ghcr.io/wg-easy/wg-easy wgpw "$wg_pass" 2>/dev/null)
        raw_hash=$(echo "$raw_output" | sed "s|PASSWORD_HASH=||" | tr -d "'" | tr -d '\r' | tr -d '\n')

        # Write .env fresh (avoids sed escaping issues)
        cat > "$dir/.env" << ENVEOF
# WG-Easy Environment Variables
# Generated by wgshield.sh

WG_HOST=${wg_host}
PASSWORD_HASH=${raw_hash}
WG_DEFAULT_DNS=10.8.1.3
WG_PORT_UDP=51820
WG_PORT_TCP=51821
WG_PASSWORD=${wg_pass}
ENVEOF
        chmod 600 "$dir/.env" 2>/dev/null || true
    fi

    chmod +x "$dir"/*.sh 2>/dev/null || true

    if ! has_docker; then
        err "${ERR_DOCKER_NOT_INSTALLED}. ${MSG_EXECUTE_DOCKER_INSTALL}"
    fi

    spinner "${MSG_LOG_STARTING} $display"
    (cd "$dir" && docker compose up -d 2>&1)
    sleep 3

    local st
    st=$(get_container_status "$container")
    if [ "$st" = "running" ]; then
        log "$display ${LOG_INSTALLED} $ports"
    else
        warn "$display ${ERR_WONT_START}. ${MSG_CHECK_LOGS}"
    fi

    show_comp_info "$comp"
}

start_comp() {
    local comp="$1"
    if ! comp_info_valid "$comp"; then
        warn "${ERR_UNKNOWN_COMP_SHORT}"
        return 1
    fi
    local dir display container
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2); container=$(parse_comp "$comp" 6)

    if ! comp_exists "$comp"; then
        warn "$display ${ERR_NOT_INSTALLED}. ${MSG_INSTALL_COMP}"
        return 1
    fi

    spinner "${MSG_LOG_STARTING} $display"
    (cd "$dir" && docker compose up -d 2>&1)
    sleep 2

    local st
    st=$(get_container_status "$container")
    [ "$st" = "running" ] && log "$display ${LOG_STARTED}" || warn "$display ${ERR_WONT_START}"
}

stop_comp() {
    local comp="$1"
    if ! comp_info_valid "$comp"; then
        warn "${ERR_UNKNOWN_COMP_SHORT}"
        return 1
    fi
    local dir display
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2)
    comp_exists "$comp" || { warn "$display ${ERR_NOT_INSTALLED}"; return 1; }

    spinner "${MSG_LOG_STOPPING} $display"
    (cd "$dir" && docker compose down --timeout 10 2>&1)
    log "$display ${MSG_STATUS_STOPPED}"
}

restart_comp() { stop_comp "$1"; start_comp "$1"; }

update_comp() {
    local comp="$1"
    local dir display container st
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2); container=$(parse_comp "$comp" 6)
    comp_exists "$comp" || { warn "$display ${ERR_NOT_INSTALLED}"; return 1; }

    create_backup "$comp" "before-update"

    spinner "${MSG_LOG_UPDATING} $display"
    if ! (cd "$dir" && git pull --quiet 2>&1); then
        warn "${ERR_GIT_PULL_FAIL}. ${MSG_GIT_PULL_CONTINUE}"
    fi

    st=$(get_container_status "$container")
    if [ "$st" = "running" ]; then
        spinner "${MSG_LOG_RESTARTING}"
        (cd "$dir" && docker compose restart 2>&1)
    else
        spinner "${MSG_LOG_STARTING} container"
        (cd "$dir" && docker compose up -d 2>&1)
    fi

    log "$display ${LOG_UPDATED}"
}

remove_comp() {
    local comp="$1"
    local dir display container
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2); container=$(parse_comp "$comp" 6)
    comp_exists "$comp" || { warn "$display ${ERR_NOT_INSTALLED}"; return 1; }

    warn "${ERR_PARAR_REMOVER} $display"
    confirm "${PROMPT_ARE_YOU_SURE}" || return 0

    create_backup "$comp" "before-remove"

    spinner "${MSG_LOG_REMOVING} $display"
    (cd "$dir" && docker compose down -v --timeout 10 2>&1)
    rm -rf "$dir"
    log "$display ${LOG_REMOVED}"
}

status_comp() {
    local comp="$1"
    if ! comp_info_valid "$comp"; then
        warn "${ERR_UNKNOWN_COMP_SHORT}"
        return 1
    fi
    local dir display ports container
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2)
    ports=$(parse_comp "$comp" 3); container=$(parse_comp "$comp" 6)

    echo ""
    echo -e "${BD}${C}=== $display ===${NC}"
    echo "  ${MSG_INFO_CUSTOM_PORT}  $dir"
    echo "  ${MSG_INFO_PORT}  $ports"

    local st
    st=$(get_container_status "$container")
    if [ "$st" = "running" ]; then
        echo -e "  Status: ${BD}${G}● ${MSG_STATUS_RUNNING}${NC}"
        show_comp_info "$comp"
    else
        echo -e "  Status: ${BD}${R}● ${MSG_STATUS_STOPPED}${NC}"
    fi
}

show_comp_info() {
    local comp="$1"
    if ! comp_info_valid "$comp"; then return 1; fi
    local dir display ports
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2); ports=$(parse_comp "$comp" 3)

    echo ""
    if [ "$comp" = "wg-easy" ]; then
        local wg_host pass
        wg_host=$(curl -s4 ifconfig.me 2>/dev/null || echo "YOUR_IP")
        [ -f "$dir/.env" ] && {
            pass=$(grep -m1 "^WG_PASSWORD=" "$dir/.env" | cut -d= -f2)
        }
        echo "  ${MSG_INFO_WG_EASY_URL}  http://${wg_host}:${MSG_INFO_WG_EASY_PORT}"
        [ -n "$pass" ] && echo "  ${MSG_INFO_WG_EASY_PASS}  $pass"
    elif [ "$comp" = "adguard" ]; then
        echo "  ${MSG_INFO_ADGUARD_URL}  http://10.8.1.3:3000"
        echo ""
        echo "  ${MSG_INFO_ADGUARD_SETUP}"
        echo "  ${MSG_INFO_ADGUARD_SETUP_2}"
        echo "  ${MSG_INFO_ADGUARD_SETUP_3}"
        echo "  ${MSG_INFO_ADGUARD_SETUP_4}"
    fi
    echo ""
}

logs_comp() {
    local comp="$1" dir display
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2)
    comp_exists "$comp" || { warn "$display ${ERR_NOT_INSTALLED}"; return 1; }

    info "${MSG_INFO_LOGS}..."
    (cd "$dir" && docker compose logs -f --no-log-prefix)
}

shell_comp() {
    local comp="$1" dir display container
    dir=$(parse_comp "$comp" 7); display=$(parse_comp "$comp" 2); container=$(parse_comp "$comp" 6)
    comp_exists "$comp" || { warn "$display ${ERR_NOT_INSTALLED}"; return 1; }

    local st
    st=$(get_container_status "$container")
    [ "$st" != "running" ] && { warn "$display ${ERR_NOT_RUNNING}. ${MSG_USE_TO_START}"; return 1; }

    (cd "$dir" && docker compose exec -it "$container" sh)
}

toggle_dns_public() {
    echo ""
    echo -e "  ${BD}${C}${MSG_DNS_TOGGLE_TITLE}${NC}"
    echo ""

    if check_module_status dns; then
        # DNS is currently public, ask to close
        echo -e "  Status ${MSG_DNS_PUBLIC}: ${G}${MSG_DNS_PUBLIC}${NC} (${MSG_DNS_OPEN_PORT})"
        echo ""
        confirm "  ${MSG_DNS_CLOSE_PORT} [Y/n]" || return 0

        # Show spinner while removing
        local pid
        (
            local chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
            local i=0
            while kill -0 $$ 2>/dev/null; do
                printf "\r  ${B}[●]${NC} ${chars:$((i % 10)):1} ${MSG_DNS_CLOSING}..."
                i=$((i + 1))
                sleep 0.1
            done
        ) &
        pid=$!

        mod_dns_remove >/dev/null 2>&1

        kill $pid 2>/dev/null
        wait $pid 2>/dev/null
        printf "\r  ${G}[✔]${NC} ${MSG_DNS_PRIVATE} - ${MSG_DNS_CLOSE_PORT}\n"
    else
        # DNS is currently private, ask to open
        echo -e "  Status ${MSG_DNS_PRIVATE}: ${MSG_DNS_PRIVATE} (${MSG_INFO_ADGUARD_SETUP})"
        echo ""
        confirm "  ${MSG_DNS_OPEN_PORT} [Y/n]" || return 0

        # Show spinner while opening
        local pid
        (
            local chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
            local i=0
            while kill -0 $$ 2>/dev/null; do
                printf "\r  ${B}[●]${NC} ${chars:$((i % 10)):1} ${MSG_DNS_OPENING}..."
                i=$((i + 1))
                sleep 0.1
            done
        ) &
        pid=$!

        mod_dns >/dev/null 2>&1

        kill $pid 2>/dev/null
        wait $pid 2>/dev/null
        printf "\r  ${G}[✔]${NC} ${MSG_DNS_PUBLIC} - ${MSG_DNS_OPEN_PORT}\n"
    fi
}

reset_wg_password() {
    local dir
    dir=$(parse_comp "wg-easy" 7)
    local display="${MSG_COMP_WG_EASY}"

    if [ ! -d "$dir" ] || [ ! -f "$dir/.env" ]; then
        warn "$display ${ERR_NOT_INSTALLED}"
        return 1
    fi

    echo ""
    echo -e "  ${BD}${C}${MSG_RESET_PASSWORD_TITLE} ${display}${NC}"
    echo ""

    # Show current password
    local current_pass
    current_pass=$(grep -m1 "^WG_PASSWORD=" "$dir/.env" 2>/dev/null | cut -d= -f2)
    if [ -n "$current_pass" ]; then
        echo -e "  ${MSG_CURRENT_PASSWORD} ${Y}${BD}${current_pass}${NC}"
        echo ""
    fi

    confirm "  ${MSG_GENERATING_PASSWORD} [Y/n]" || return 0

    # Show spinner while generating
    local pid
    (
        local chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
        local i=0
        while kill -0 $$ 2>/dev/null; do
            printf "\r  ${B}[●]${NC} ${chars:$((i % 10)):1} ${MSG_GENERATING_PASSWORD}"
            i=$((i + 1))
            sleep 0.1
        done
    ) &
    pid=$!

    # Generate new password and hash
    local new_pass wg_host raw_output raw_hash
    new_pass=$(openssl rand -hex 8)
    wg_host=$(curl -s4 ifconfig.me 2>/dev/null || echo "YOUR_IP")
    raw_output=$(docker run --rm ghcr.io/wg-easy/wg-easy wgpw "$new_pass" 2>/dev/null)
    raw_hash=$(echo "$raw_output" | sed "s|PASSWORD_HASH=||" | tr -d "'" | tr -d '\r' | tr -d '\n')

    # Write .env file fresh (avoids sed issues with $ in bcrypt)
    cat > "$dir/.env" << ENVEOF
# WG-Easy Environment Variables
# Generated automatically by wgshield.sh

WG_HOST=${wg_host}
PASSWORD_HASH=${raw_hash}
WG_DEFAULT_DNS=10.8.1.3
WG_PORT_UDP=51820
WG_PORT_TCP=51821
WG_PASSWORD=${new_pass}
ENVEOF
    chmod 600 "$dir/.env" 2>/dev/null || true

    kill $pid 2>/dev/null
    wait $pid 2>/dev/null
    printf "\r  ${G}[✔]${NC} ${MSG_RESET_NEW_PASSWORD}\n"

    # Restart container
    local pid2
    (
        local chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
        local i=0
        while kill -0 $$ 2>/dev/null; do
            printf "\r  ${B}[●]${NC} ${chars:$((i % 10)):1} ${MSG_RESET_RESTARTING}"
            i=$((i + 1))
            sleep 0.1
        done
    ) &
    pid2=$!

    # Restart container with down/up to re-read .env
    (cd "$dir" && docker compose down --timeout 10 && docker compose up -d 2>&1) >/dev/null
    sleep 3

    kill $pid2 2>/dev/null
    wait $pid2 2>/dev/null
    printf "\r  ${G}[✔]${NC} ${MSG_RESET_CONTAINER_RESTARTED}\n"

    echo ""
    echo -e "  ${BD}${C}${MSG_RESET_NEW_CREDS}${NC}"
    echo "    ${MSG_RESET_URL}  http://${wg_host}:${MSG_INFO_WG_EASY_PORT}"
    echo -e "    ${MSG_NEW_PASSWORD} ${G}${BD}${new_pass}${NC}"
}
